### ISSUE TITLE
Similar projects that can be of interest

### ISSUE THREAD

**Issue by mingodad** [tokay-lang/tokay#20]
I found some projects that have a similar objective as this one:

- An experiment in language design, employing a dynamically exstensible LALR(1) parser. https://github.com/waywardgeek/not_rune
- n addition to many other features it provides an extension mechanism. Seed7 supports the introduction of new syntax and their semantics into the language and it allows new language constructs to be defined using the Seed7 language itself. E.g.: Programmers can introduce syntax and semantic of new statements as well as user defined operator symbols. http://seed7.sourceforge.net/
- Jeebox tries to fulfil the goal of describing everything https://github.com/gamblevore/jeebox
- http://mbeddr.com/
- A more descriptive text and a list of examples https://en.wikipedia.org/wiki/Extensible_programming

**Comment by phorward** [comment]
Hello @mingodad, thanks for creating this issue with project links.

Well, Tokay follows another design principle, as it executes programs in a way similar to the awk programming language, but allowing to run grammar-like constructs. Therefore, it is not an extensible programming language or experimental project (thought, it is some kind of experiment, but with a useful goal).

Tokay is intended to become a tool for everyday use especially when working with the command-line, in combination with shell scripts, to write tools for data extraction or rewriting syntactical portions of code where a regular expression does not satisfy. Therefore, a LR-based attempt is not followed, but a practical, packrat-based top-down parser, which executes code during parsing the program, but without code-bloat.
